const withDomains = (card) => ({
  ...card,
  domains: {
    relationship: card.domains?.relationship || '상대의 속도를 존중하며 부드럽게 대화해 보세요.',
    work: card.domains?.work || '가장 중요한 일 하나를 먼저 정리해 보세요.',
    money: card.domains?.money || '충동보다 필요를 기준으로 선택해 보세요.',
    health: card.domains?.health || '컨디션의 작은 신호를 가볍게 넘기지 마세요.',
  },
});

export const MAJOR_ARCANA = [
  withDomains({
    id: 'm00',
    name: 'The Fool',
    nameKr: '0. 바보',
    image: require('../../assets/card/0. The Fool.png'),
    keywords: ['시작', '자유', '호기심', '가능성', '가벼운 발걸음'],
    light: '새로운 가능성을 가볍게 열어 보기 좋은 날',
    shadow: '준비 없이 움직이면 작은 실수가 커질 수 있는 날',
    advice: '완벽함보다 첫걸음을 작게 시작해 보세요.',
    domains: {
      relationship: '낯선 대화도 열린 마음으로 받아들이면 좋습니다.',
      work: '새 아이디어를 시험하되 기본 확인은 놓치지 마세요.',
      money: '즉흥 소비보다 작은 경험에 투자해 보세요.',
      health: '활동량을 늘리되 무리한 도전은 피하세요.',
    },
  }),
  withDomains({
    id: 'm01',
    name: 'The Magician',
    nameKr: '1. 마법사',
    image: require('../../assets/card/1. The Magician.png'),
    keywords: ['실행력', '도구', '집중', '표현', '시작의 힘'],
    light: '가진 자원을 잘 조합해 결과를 만들기 좋은 날',
    shadow: '말과 계획이 앞서 실제 행동이 부족해지기 쉬운 날',
    advice: '이미 가진 도구 하나를 골라 바로 실행해 보세요.',
    domains: {
      relationship: '분명하고 솔직한 표현이 관계를 부드럽게 합니다.',
      work: '흩어진 일을 하나의 우선순위로 묶어 보세요.',
      money: '새 수익보다 현재 자원을 점검하는 데 유리합니다.',
      health: '몸의 신호를 기록하며 루틴을 정돈해 보세요.',
    },
  }),
  withDomains({
    id: 'm02',
    name: 'The High Priestess',
    nameKr: '2. 여사제',
    image: require('../../assets/card/2. The High Priestess.png'),
    keywords: ['직관', '침묵', '관찰', '내면', '비밀'],
    light: '말보다 감각과 관찰이 중요한 단서를 주는 날',
    shadow: '혼자 추측하다가 오해를 키우기 쉬운 날',
    advice: '바로 판단하지 말고 한 번 더 관찰해 보세요.',
    domains: {
      relationship: '상대의 속도를 존중하며 듣는 시간이 필요합니다.',
      work: '드러난 정보보다 빠진 부분을 확인해 보세요.',
      money: '결정 전 조건과 작은 글씨를 차분히 읽어 보세요.',
      health: '휴식 부족이 예민함으로 이어지지 않게 하세요.',
    },
  }),
  withDomains({
    id: 'm03',
    name: 'The Empress',
    nameKr: '3. 여황제',
    image: require('../../assets/card/3. The Empress.png'),
    keywords: ['풍요', '돌봄', '창조성', '감각', '성장'],
    light: '돌봄과 창조성이 자연스럽게 흐르는 날',
    shadow: '편안함에 기대어 해야 할 일을 미루기 쉬운 날',
    advice: '나와 주변을 살리는 작은 배려를 실천해 보세요.',
    domains: {
      relationship: '따뜻한 말 한마디가 관계의 긴장을 낮춥니다.',
      work: '아이디어를 보기 좋게 다듬으면 설득력이 커집니다.',
      money: '기분 지출을 줄이고 필요한 만족을 골라 보세요.',
      health: '식사와 수면처럼 기본 돌봄을 우선하세요.',
    },
  }),
  withDomains({
    id: 'm04',
    name: 'The Emperor',
    nameKr: '4. 황제',
    image: require('../../assets/card/4. The Emperor.png'),
    keywords: ['질서', '책임', '기준', '안정', '리더십'],
    light: '기준을 세우고 흐름을 안정시키기 좋은 날',
    shadow: '내 방식만 고집하면 주변과 부딪히기 쉬운 날',
    advice: '규칙을 세우되 유연하게 조정할 여지를 남기세요.',
    domains: {
      relationship: '약속과 경계를 명확히 하면 편안해집니다.',
      work: '해야 할 일을 순서대로 정리하면 속도가 납니다.',
      money: '예산과 고정 지출을 점검하기 좋은 날입니다.',
      health: '무리한 버티기보다 안정적인 루틴을 지키세요.',
    },
  }),
  withDomains({
    id: 'm05',
    name: 'The Hierophant',
    nameKr: '5. 교황',
    image: require('../../assets/card/5. The Hierophant.png'),
    keywords: ['전통', '배움', '조언', '가치관', '신뢰'],
    light: '믿을 만한 기준과 조언이 방향을 잡아 주는 날',
    shadow: '남의 기준에 맞추느라 내 마음을 놓치기 쉬운 날',
    advice: '검증된 방법을 참고하되 내 상황에 맞게 적용하세요.',
    domains: {
      relationship: '예의를 갖춘 대화가 오해를 줄여 줍니다.',
      work: '매뉴얼이나 선례를 확인하면 실수를 줄일 수 있습니다.',
      money: '익숙한 방식의 관리가 오늘은 더 안전합니다.',
      health: '전문가의 기본 조언을 가볍게 넘기지 마세요.',
    },
  }),
  withDomains({
    id: 'm06',
    name: 'The Lovers',
    nameKr: '6. 연인',
    image: require('../../assets/card/6. The Lovers.png'),
    keywords: ['선택', '조화', '끌림', '관계', '가치'],
    light: '마음이 향하는 것과 중요한 가치를 맞춰 보기 좋은 날',
    shadow: '끌림만 따라가면 선택의 기준이 흐려질 수 있는 날',
    advice: '좋아하는 마음과 오래 지킬 기준을 함께 보세요.',
    domains: {
      relationship: '진심을 확인하는 부드러운 대화가 도움이 됩니다.',
      work: '협업에서는 서로의 기대치를 먼저 맞춰 보세요.',
      money: '욕구와 필요를 구분하면 후회가 줄어듭니다.',
      health: '몸이 원하는 편안함과 필요한 관리를 균형 있게 보세요.',
    },
  }),
  withDomains({
    id: 'm07',
    name: 'Chariot',
    nameKr: '7. 전차',
    image: require('../../assets/card/7. Chariot.png'),
    keywords: ['추진력', '집중', '승부', '이동', '방향'],
    light: '목표를 정하면 힘 있게 밀고 나갈 수 있는 날',
    shadow: '속도에 취해 주변 신호를 놓치기 쉬운 날',
    advice: '방향을 먼저 확인한 뒤 속도를 내세요.',
    domains: {
      relationship: '내 주장만 앞세우지 않으면 대화가 잘 풀립니다.',
      work: '짧은 시간 집중해 핵심 과제를 끝내기 좋습니다.',
      money: '빠른 결정보다 목표에 맞는지 확인이 필요합니다.',
      health: '운동은 좋지만 과한 경쟁심은 내려놓으세요.',
    },
  }),
  withDomains({
    id: 'm08',
    name: 'Strength',
    nameKr: '8. 힘',
    image: require('../../assets/card/8. Strength.png'),
    keywords: ['인내', '용기', '부드러운 힘', '절제', '회복'],
    light: '부드럽게 버티는 힘이 상황을 안정시키는 날',
    shadow: '참기만 하다가 피로가 쌓이기 쉬운 날',
    advice: '강하게 밀기보다 차분히 조율해 보세요.',
    domains: {
      relationship: '따뜻하지만 분명한 태도가 관계를 지켜 줍니다.',
      work: '어려운 일도 작은 단위로 나누면 감당할 수 있습니다.',
      money: '충동을 한 번 넘기면 만족스러운 선택이 됩니다.',
      health: '긴장을 풀어 주는 호흡과 스트레칭이 좋습니다.',
    },
  }),
  withDomains({
    id: 'm09',
    name: 'The Hermit',
    nameKr: '9. 은둔자',
    image: require('../../assets/card/9. The Hermit.png'),
    keywords: ['성찰', '거리두기', '지혜', '탐색', '고요'],
    light: '잠시 물러나 내 답을 찾기 좋은 날',
    shadow: '고립이 길어지면 도움을 놓치기 쉬운 날',
    advice: '혼자 생각하되 필요한 질문은 밖으로 꺼내세요.',
    domains: {
      relationship: '잠깐의 거리두기가 감정을 정리해 줍니다.',
      work: '깊이 생각해야 하는 일에 집중하기 좋습니다.',
      money: '소비보다 기록과 분석에 어울리는 날입니다.',
      health: '조용한 휴식으로 에너지를 회복해 보세요.',
    },
  }),
  withDomains({
    id: 'm10',
    name: 'Wheel of Fortune',
    nameKr: '10. 운명의 수레바퀴',
    image: require('../../assets/card/10. Wheel of Fortune.png'),
    keywords: ['전환', '흐름', '기회', '변화', '타이밍'],
    light: '흐름의 전환을 유연하게 타기 좋은 날',
    shadow: '상황 변화에 휩쓸려 중심을 잃기 쉬운 날',
    advice: '예상 밖 변화가 와도 선택 가능한 한 가지를 찾으세요.',
    domains: {
      relationship: '우연한 대화에서 관계의 힌트를 얻을 수 있습니다.',
      work: '일정 변화에 대비해 우선순위를 열어 두세요.',
      money: '변동성이 큰 선택은 여유를 두고 판단하세요.',
      health: '컨디션 변화에 맞춰 계획을 가볍게 조정하세요.',
    },
  }),
  withDomains({
    id: 'm11',
    name: 'Justice',
    nameKr: '11. 정의',
    image: require('../../assets/card/11. Justice.png'),
    keywords: ['균형', '판단', '책임', '공정함', '정리'],
    light: '사실과 감정을 균형 있게 보고 정리하기 좋은 날',
    shadow: '옳고 그름에만 매달리면 마음이 딱딱해질 수 있는 날',
    advice: '판단 전 사실, 감정, 책임을 따로 적어 보세요.',
    domains: {
      relationship: '공정한 태도가 신뢰를 회복하는 데 도움이 됩니다.',
      work: '문서와 약속을 꼼꼼히 확인하기 좋은 날입니다.',
      money: '수입과 지출의 균형을 숫자로 확인해 보세요.',
      health: '생활 습관의 원인과 결과를 차분히 살펴보세요.',
    },
  }),
  withDomains({
    id: 'm12',
    name: 'The Hanged Man',
    nameKr: '12. 매달린 사람',
    image: require('../../assets/card/12. The Hanged Man.png'),
    keywords: ['멈춤', '관점 전환', '기다림', '수용', '재해석'],
    light: '잠시 멈추면 다른 관점이 열리는 날',
    shadow: '아무것도 못 한다는 답답함에 갇히기 쉬운 날',
    advice: '지금 당장 바꿀 수 없는 것과 할 수 있는 일을 나누세요.',
    domains: {
      relationship: '상대 입장에서 보면 대화의 실마리가 보입니다.',
      work: '막힌 일은 순서를 바꾸거나 잠시 쉬어 가세요.',
      money: '큰 지출은 보류하고 필요성을 다시 점검하세요.',
      health: '몸이 보내는 쉬라는 신호를 존중해 주세요.',
    },
  }),
  withDomains({
    id: 'm13',
    name: 'Death',
    nameKr: '13. 죽음',
    image: require('../../assets/card/13. Death.png'),
    keywords: ['마무리', '전환', '정리', '새 단계', '비움'],
    light: '낡은 흐름을 정리하고 새 공간을 만들기 좋은 날',
    shadow: '끝을 두려워해 필요한 변화를 미루기 쉬운 날',
    advice: '오늘 끝낼 수 있는 작은 미련 하나를 내려놓으세요.',
    domains: {
      relationship: '묵은 감정은 차분히 정리하고 새 대화를 준비하세요.',
      work: '불필요한 업무나 파일을 정리하면 집중이 돌아옵니다.',
      money: '사용하지 않는 구독이나 지출을 줄이기 좋습니다.',
      health: '몸에 부담 되는 습관 하나를 가볍게 끊어 보세요.',
    },
  }),
  withDomains({
    id: 'm14',
    name: 'Temperance',
    nameKr: '14. 절제',
    image: require('../../assets/card/14. Temperance.png'),
    keywords: ['균형', '조율', '회복', '중도', '리듬'],
    light: '서로 다른 흐름을 차분히 섞어 균형을 찾는 날',
    shadow: '극단적인 선택이 피로를 키우기 쉬운 날',
    advice: '한쪽으로 치우친 일정을 중간 지점으로 조정하세요.',
    domains: {
      relationship: '속도를 맞추는 태도가 관계를 편안하게 합니다.',
      work: '완급 조절을 하면 오래 집중할 수 있습니다.',
      money: '저축과 소비의 균형을 다시 맞춰 보세요.',
      health: '수분, 식사, 휴식의 리듬을 고르게 챙기세요.',
    },
  }),
  withDomains({
    id: 'm15',
    name: 'The Devil',
    nameKr: '15. 악마',
    image: require('../../assets/card/15. The Devil.png'),
    keywords: ['집착', '유혹', '습관', '욕망', '묶임'],
    light: '내가 반복하는 패턴을 솔직히 알아차리기 좋은 날',
    shadow: '즉각적인 만족에 끌려 선택이 흐려질 수 있는 날',
    advice: '나를 묶는 습관 하나를 이름 붙여 보세요.',
    domains: {
      relationship: '집착보다 솔직한 욕구 표현이 필요합니다.',
      work: '미루게 만드는 유혹을 환경에서 잠시 치워 보세요.',
      money: '충동구매 버튼을 누르기 전 하루만 보류하세요.',
      health: '과식, 과로, 과몰입의 신호를 가볍게 끊어 주세요.',
    },
  }),
  withDomains({
    id: 'm16',
    name: 'The Tower',
    nameKr: '16. 탑',
    image: require('../../assets/card/16. The Tower.png'),
    keywords: ['깨달음', '흔들림', '해체', '진실', '재정비'],
    light: '흔들림 속에서 진짜 필요한 구조를 볼 수 있는 날',
    shadow: '갑작스러운 변화에 놀라 과하게 반응하기 쉬운 날',
    advice: '무너진 것보다 다시 세울 기준을 먼저 찾으세요.',
    domains: {
      relationship: '불편한 진실도 차분히 말하면 정리가 시작됩니다.',
      work: '문제가 드러나면 탓보다 구조 개선에 집중하세요.',
      money: '예상 밖 지출에 대비해 여유분을 확인하세요.',
      health: '갑작스러운 무리보다 안전한 회복을 우선하세요.',
    },
  }),
  withDomains({
    id: 'm17',
    name: 'The Star',
    nameKr: '17. 별',
    image: require('../../assets/card/17. The Star.png'),
    keywords: ['희망', '회복', '영감', '진정성', '믿음'],
    light: '작은 희망과 회복의 감각을 되찾기 좋은 날',
    shadow: '멀리 있는 이상만 보다가 지금 할 일을 놓치기 쉬운 날',
    advice: '큰 꿈을 오늘의 작은 행동 하나로 낮춰 보세요.',
    domains: {
      relationship: '진심 어린 격려가 관계에 빛을 더합니다.',
      work: '장기 목표를 떠올리면 현재 과제의 의미가 보입니다.',
      money: '미래 계획을 위한 작은 저축이 잘 어울립니다.',
      health: '회복을 돕는 가벼운 산책이나 물 마시기가 좋습니다.',
    },
  }),
  withDomains({
    id: 'm18',
    name: 'The Moon',
    nameKr: '18. 달',
    image: require('../../assets/card/18. The Moon.png'),
    keywords: ['직감', '불안', '무의식', '숨겨진 감정', '착각'],
    light: '흐릿했던 감정과 신호를 섬세하게 감지하는 날',
    shadow: '확인되지 않은 상상이나 불안으로 결론을 내리기 쉬운 날',
    advice: '중요한 판단은 서두르지 말고 감정을 먼저 정리하세요.',
    domains: {
      relationship: '상대의 말보다 분위기에 예민해질 수 있습니다.',
      work: '불확실한 정보가 많으니 확인 과정을 거치는 것이 좋습니다.',
      money: '충동적인 지출이나 불안 기반 선택을 피하세요.',
      health: '수면과 감정 기복을 가볍게 넘기지 마세요.',
    },
  }),
  withDomains({
    id: 'm19',
    name: 'The Sun',
    nameKr: '19. 태양',
    image: require('../../assets/card/19. The Sun.png'),
    keywords: ['활력', '명확함', '기쁨', '성취', '개방감'],
    light: '밝고 명확한 에너지가 자신감을 돕는 날',
    shadow: '낙관이 지나치면 세부 확인을 놓치기 쉬운 날',
    advice: '좋은 에너지를 주변과 나누되 기본은 확인하세요.',
    domains: {
      relationship: '밝은 표현과 칭찬이 관계를 따뜻하게 합니다.',
      work: '성과를 드러내고 공유하기 좋은 타이밍입니다.',
      money: '기분 좋은 소비도 예산 안에서 즐겨 보세요.',
      health: '햇빛과 가벼운 움직임이 활력을 올려 줍니다.',
    },
  }),
  withDomains({
    id: 'm20',
    name: 'Judgement',
    nameKr: '20. 심판',
    image: require('../../assets/card/20. Judgement.png'),
    keywords: ['각성', '회고', '결정', '부름', '재시작'],
    light: '지난 일을 돌아보고 다음 결정을 내리기 좋은 날',
    shadow: '후회에 머물면 다시 시작할 힘이 약해질 수 있는 날',
    advice: '자책보다 배운 점 하나를 다음 행동으로 바꾸세요.',
    domains: {
      relationship: '미뤄 둔 대화에 정중히 응답하기 좋습니다.',
      work: '지난 결과를 리뷰하면 다음 개선점이 분명해집니다.',
      money: '과거 지출 패턴에서 반복되는 신호를 찾아보세요.',
      health: '몸의 오래된 신호를 점검하고 관리 계획을 세우세요.',
    },
  }),
  withDomains({
    id: 'm21',
    name: 'The World',
    nameKr: '21. 세계',
    image: require('../../assets/card/21. The World.png'),
    keywords: ['완성', '통합', '확장', '성취', '마무리'],
    light: '하나의 사이클을 정리하고 넓은 시야를 얻는 날',
    shadow: '완성감에 머물러 다음 연결을 놓치기 쉬운 날',
    advice: '마무리를 축하하고 다음 단계의 작은 문을 열어 보세요.',
    domains: {
      relationship: '서로의 성장을 인정하면 관계가 더 넓어집니다.',
      work: '완료한 일을 정리하고 공유하면 가치가 커집니다.',
      money: '장기 계획을 점검하고 다음 목표를 세우기 좋습니다.',
      health: '전체 생활 리듬을 돌아보고 균형을 맞춰 보세요.',
    },
  }),
];
