export const MAJOR_ARCANA = [
  { id: 'm00', name: 'The Fool', nameKr: '0. 광대', image: require('../../assets/card/0. The Fool.png') },
  { id: 'm01', name: 'The Magician', nameKr: '1. 마법사', image: require('../../assets/card/1. The Magician.png') },
  { id: 'm02', name: 'The High Priestess', nameKr: '2. 여사제', image: require('../../assets/card/2. The High Priestess.png') },
  { id: 'm03', name: 'The Empress', nameKr: '3. 여황제', image: require('../../assets/card/3. The Empress.png') },
  { id: 'm04', name: 'The Emperor', nameKr: '4. 황제', image: require('../../assets/card/4. The Emperor.png') },
  { id: 'm05', name: 'The Hierophant', nameKr: '5. 교황', image: require('../../assets/card/5. The Hierophant.png') },
  { id: 'm06', name: 'The Lovers', nameKr: '6. 연인', image: require('../../assets/card/6. The Lovers.png') },
  { id: 'm07', name: 'Chariot', nameKr: '7. 전차', image: require('../../assets/card/7. Chariot.png') },
  { id: 'm08', name: 'Strength', nameKr: '8. 힘', image: require('../../assets/card/8. Strength.png') },
  { id: 'm09', name: 'The Hermit', nameKr: '9. 은둔자', image: require('../../assets/card/9. The Hermit.png') },
  { id: 'm10', name: 'Wheel of Fortune', nameKr: '10. 운명의 수레바퀴', image: require('../../assets/card/10. Wheel of Fortune.png') },
  { id: 'm11', name: 'Justice', nameKr: '11. 정의', image: require('../../assets/card/11. Justice.png') },
  { id: 'm12', name: 'The Hanged Man', nameKr: '12. 매달린 사람', image: require('../../assets/card/12. The Hanged Man.png') },
  { id: 'm13', name: 'Death', nameKr: '13. 죽음', image: require('../../assets/card/13. Death.png') },
  { id: 'm14', name: 'Temperance', nameKr: '14. 절제', image: require('../../assets/card/14. Temperance.png') },
  { id: 'm15', name: 'The Devil', nameKr: '15. 악마', image: require('../../assets/card/15. The Devil.png') },
  { id: 'm16', name: 'The Tower', nameKr: '16. 탑', image: require('../../assets/card/16. The Tower.png') },
  { id: 'm17', name: 'The Star', nameKr: '17. 별', image: require('../../assets/card/17. The Star.png') },
  { id: 'm18', name: 'The Moon', nameKr: '18. 달', image: require('../../assets/card/18. The Moon.png') },
  { id: 'm19', name: 'The Sun', nameKr: '19. 태양', image: require('../../assets/card/19. The Sun.png') },
  { id: 'm20', name: 'Judgement', nameKr: '20. 심판', image: require('../../assets/card/20. Judgement.png') },
  { id: 'm21', name: 'The World', nameKr: '21. 세계', image: require('../../assets/card/21. The World.png') },
];
